inherit_from: .rubocop_todo.yml

require:
- rubocop-rspec
- rubocop-performance
- rubocop-sequel

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - "longleaf.gemspec"

Layout/IndentationConsistency:
  EnforcedStyle: normal

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

Rails:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

# https://github.com/rubocop-hq/rubocop/issues/6439
Style/AccessModifierDeclarations:
  Enabled: false

Style/StringLiterals:
  Enabled: false
