site_name: Longleaf Documentation
site_url: https://unc-libraries.github.io/longleaf-preservation
theme: readthedocs
# repo_name: 'UNC-Libraries/Longleaf-preservation'
#setting edit_uri to empty string removes the "Edit in" link in upper right hand corner of pages, but keeps the Github link to repo in the bottom of sidepane
repo_url: https://github.com/UNC-Libraries/longleaf-preservation/
site_description: Longleaf is a command-line tool which allows users to configure a set of storage locations and define custom sets of preservation services to run on their contents. These services are executed in response to applicable preservation events issued by clients. Its primary goal is to provide tools to create a simple and customizable preservation environment.
edit_uri: ''

# include extra css file, in docs/
extra_css: [extra.css]

# docs markdown pages to include in sidepane navigation
nav:
    - Welcome: index.md
    - About Longleaf: aboutlongleaf.md
    - Installation: install.md
    - Basic Usage: quickstart.md
# pages to add and include later
#    - Troubleshooting: trouble.md
#    - FAQs: faq.md
