#!/usr/bin/env ruby

if RUBY_ENGINE == 'jruby'
  require 'java'
  ENV['JARS_LOCK'] = File.expand_path('../../Jars.lock', __FILE__)
  ENV['JARS_HOME'] = File.join(ENV_JAVA['user.home'], '.m2', 'repository')
  require 'jars/setup'
end

require 'longleaf/cli'
Longleaf::CLI.start
